spring.application.name=DynamoBackend


spring.datasource.url=jdbc:sqlserver://10.60.253.11;database=dynamo;trustServerCertificate=false;encrypt=false;
spring.datasource.url=jdbc:sqlserver://localhost;database=MyDB;trustServerCertificate=false;encrypt=false;
spring.datasource.username=admin
spring.datasource.password=123456789

# spring.datasource.url=jdbc:mysql://localhost:3306/mybd
# spring.datasource.username=root
# spring.datasource.password=admin


spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# spring.sql.init.platform=mysql
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.jpa.hibernate.ddl-auto=none

spring.main.allow-circular-references=true
# Email Configuration (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vy.hoangthi.cit21@eiu.edu.vn
spring.mail.password=yiuncxidqrkzpfun
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*

# Frontend URL for reset links
app.frontend.url=http://10.70.173.140:3000 

# token for user login
jwt.secret=fcef9ed59eff544dd422836e99c1137552c1a64ea8ad030a442ff8b12548df66
jwt.expiration=900000
refresh.token.expiration=604800000

