ALTER TABLE refresh_tokens 
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE current_staff
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE group_kpi
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE machine_daily
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE machine_kpi
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE machine_segment
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE process_shift
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE process_time
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE process_time_summary
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE report
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;


ALTER TABLE staff_kpi
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `tbl-plan`
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE temp_process
MODIFY id BIGINT NOT NULL AUTO_INCREMENT;